name: My_First_Action

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Greetings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Say Hello World
        run: echo Hello world!
        
      - name: create a directory named plop
        run: mkdir plop
        
      - name: redirect ls in a file
        run: ls -a > log.txt
        
      - name: move log.txt in plop
        run: mv log.txt plop
        
      - name: ls plop
        run: ls plop
