name: Multi OS

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:

  WinduntuOS:
    name : WinduntuOS
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    if: "!contains(github.event.head_commit.message, '[skip compatibility]')"
    runs-on: ${{ matrix.os }}
       
    steps:
      - run: |
          echo "Hello from $RUNNER_OS"
          make -C ../..
